services:
  web:
    image: odoo:17.0
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - "8069:8069"
    volumes:
      - "./config:/etc/odoo"
    healthcheck:
      test: curl --fail http://localhost:8069/web/login || exit 1
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo 
    volumes:
      - "./data/db:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

