name: Publish to PyPI

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build tools
        run: |
          python -m pip install --upgrade build

      - name: Build the package
        run: |
          python -m build

      - name: Upload built package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-distributions
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: build  # Only publish if build succeeds
    permissions:
      id-token: write
    environment:
      name: pypi
      url: "https://pypi.org/p/mccann_hub-odoo_client_lib"
    steps:
      - name: Download built package
        uses: actions/download-artifact@v4
        with:
          name: package-distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true

  upload-to-release:
    runs-on: ubuntu-latest
    needs: build # Only upload to release if build succeeds
    permissions:
      contents: write  # Required to upload assets to the release
    steps:
      - name: Download built package
        uses: actions/download-artifact@v4
        with:
          name: package-distributions
          path: dist/

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*

  verify:
    runs-on: ubuntu-latest
    needs: publish  # Only verify if PyPI upload succeeds
    steps:
      - name: Install package from PyPI
        run: |
          python -m pip install mccann_hub-odoo_client_lib

      - name: Verify import
        run: |
          python -c "import mccann_hub.odoolib; print('✅ Import successful')"
