name: Discover and Run unit tests

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  run_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start up containers
        run: |
          docker compose -f ./test_containers/compose.yaml up --detach --wait --wait-timeout 600

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          PYTHONPATH=src python -m unittest discover -s tests
