name: Publish to TestPyPI

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build tools
        run: |
          python -m pip install --upgrade build

      - name: Build the package
        run: |
          python -m build

      - name: Upload built package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-distributions
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: build  # Only publish if build succeeds
    permissions:
      id-token: write
    environment:
      name: testpypi
      url: "https://test.pypi.org/p/mccann_hub-odoo_client_lib"
    steps:
      - name: Download built package
        uses: actions/download-artifact@v4
        with:
          name: package-distributions
          path: dist/

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: "https://test.pypi.org/legacy/"
          skip-existing: true
          verbose: true

  verify:
    runs-on: ubuntu-latest
    needs: publish  # Only verify if TestPyPI upload succeeds
    steps:
      - name: Install package from TestPyPI
        run: |
          python -m pip install \
            --index-url https://test.pypi.org/simple/ \
            --extra-index-url https://pypi.org/simple/ \
            mccann_hub-odoo_client_lib

      - name: Verify import
        run: |
          python -c "import mccann_hub.odoolib; print('✅ Import successful')"
